package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lib",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob(["**/*.h"]),
    strip_include_prefix = "/src/cpp/lib/",
    include_prefix = "midier",
)
